language: objective-c
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods
script:
  - xctool -workspace Example/CJKit.xcworkspace -scheme CJKit -sdk iphonesimulator test
branches:
  only:
    - master
