language: objective-c
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods
script:
  - xctool -workspace CJAPIClient.xcworkspace -scheme CJAPIClient -sdk iphonesimulator test
branches:
  only:
    - master
