language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
  - export LANG=en_US.UTF-8
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods
  - cd Example
  - pod install
  - cd ../
script:
  - xctool -workspace Example/CJKit.xcworkspace -scheme CJKit -sdk iphonesimulator test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - ./script/coveralls.rb --extension m --exclude-folder Example
branches:
  only:
    - master
